language: r
cache: packages
sudo: false
latex: false
pandoc: false

r:
  - release

# Add GDAL, GEOS, proj, and units2 dependencies.
before_install:
#  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
#  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

# Binary versions of packages to reduce build time.
r_binary_packages:
  - dplyr
  - markdown
  - units
  - digest
  - readr
  - httr
  - purrr
  - rlang
  - rvest
  - tibble
  - units
  - sf
  - tidyr
  - ggplot2
